/* Amplify Params - DO NOT EDIT
	API_HEALTHBACKEND_GRAPHQLAPIIDOUTPUT
	API_HEALTHBACKEND_PRODUCTIMAGETABLE_ARN
	API_HEALTHBACKEND_PRODUCTIMAGETABLE_NAME
	API_HEALTHBACKEND_PRODUCTTABLE_ARN
	API_HEALTHBACKEND_PRODUCTTABLE_NAME
	API_HEALTHBACKEND_VARIANTTABLE_ARN
	API_HEALTHBACKEND_VARIANTTABLE_NAME
	AUTH_HEALTHBACKEND316F331A316F331A_USERPOOLID
	ENV
	REGION
	STORAGE_HEALTHSTATICBUCKET_BUCKETNAME
Amplify Params - DO NOT EDIT */

/**
 * @type {import('@types/aws-lambda').APIGatewayProxyHandler}
 */
exports.handler = async (event) => {
	console.log(`EVENT: ${JSON.stringify(event)}`);
	return { success: true };
};
